name: Create Fancy HTML Report

on:
  workflow_call:

jobs:
  create-fancy-html-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Node.js dependencies
        run: npm ci
      - name: Downloading Cucumber report
        uses: actions/download-artifact@v4.1.7
        with:
          name: cucumber-test-report
          path: cypress/reports/json
      - name: Creating HTML report from Cucumber report
        run: npm run create-fancy-html-report
      - name: Save fancy HTML report as artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: fancy-html-test-report
          path: cypress/reports/fancy-html
