name: Execute Cypress Test Suite

on:
  workflow_call:
    secrets:
      CYPRESS_RECORD_KEY:
        required: true

jobs:
  cypress-electron-desktop:
    runs-on: ubuntu-latest
    strategy:
      # When one test fails, do NOT cancel the other containers, because this will kill Cypress processes,
      # leaving the Dashboard hanging, see https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # run 3 copies of the current job in parallel
        containers: [ 1, 2, 3 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6.6.1
        continue-on-error: true
        with:
          record: true
          parallel: true
          browser: electron
          config: "specPattern=**/Done/*.feature,viewportWidth=1920,viewportHeight=1080"
          group: "Electron - Desktop"
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Archive test reports
        uses: actions/upload-artifact@v4.3.1
        with:
          name: test-reports
          path: cypress/reports
      - name: Save simple HTML report as artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: simple-html-test-report
          path: cypress/reports/html-basic
