name: Cypress Tests

on: [push]

jobs:
  cypress-electron-desktop:
    runs-on: ubuntu-latest
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # run 3 copies of the current job in parallel
        containers: [ 1, 2, 3 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6.6.1
        continue-on-error: true
        with:
          record: true
          parallel: true
          browser: electron
          config: "specPattern=**/Done/*.feature,viewportWidth=1920,viewportHeight=1080"
          group: "Electron - Desktop"
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create fancy HTML report
        run: npm run create-fancy-html-report
      - name: Archive test reports
        uses: actions/upload-artifact@v4.3.1
        with:
          name: test-reports
          path: cypress/reports
      - name: Upload test results
        run: npm run upload-test-results
        env:
          XRAY_API_CLIENT_ID: ${{ secrets.XRAY_API_CLIENT_ID }}
          XRAY_API_CLIENT_SECRET: ${{ secrets.XRAY_API_CLIENT_SECRET }}
