name: Cypress Tests

on: [push]

jobs:
  cypress-electron-desktop:
    runs-on: ubuntu-latest
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # run 3 copies of the current job in parallel
        containers: [ 1, 2, 3 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.0
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5.0.9
        continue-on-error: true
        with:
          record: true
          parallel: true
          browser: electron
          config: "specPattern=**/Done/*.feature,viewportWidth=1920,viewportHeight=1080"
          group: "Electron - Desktop"
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create fancy HTML report
        run: npm run create-fancy-html-report
      - name: Archive test reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: cypress/reports
      - name: Archive videos
        uses: actions/upload-artifact@v3
        with:
          name: videos
          path: cypress/videos
      - name: Upload test results
        run: npm run upload-test-results
        env:
          # pass the Xray credentials as environment variables
          XRAY_API_CLIENT_ID: ${{ secrets.XRAY_API_CLIENT_ID }}
          XRAY_API_CLIENT_SECRET: ${{ secrets.XRAY_API_CLIENT_SECRET }}

#  cypress-firefox-mobile:
#    runs-on: ubuntu-latest
#    container:
#      image: cypress/browsers:node16.13.2-chrome100-ff98
#      options: --user 1001
#    strategy:
#      # when one test fails, DO NOT cancel the other
#      # containers, because this will kill Cypress processes
#      # leaving the Dashboard hanging ...
#      # https://github.com/cypress-io/github-action/issues/48
#      fail-fast: false
#      matrix:
#        # run 3 copies of the current job in parallel
#        containers: [ 1, 2, 3 ]
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3.5.0
#      # Install NPM dependencies, cache them correctly
#      # and run all Cypress tests
#      - name: Cypress run
#        uses: cypress-io/github-action@v4.1.1
#        with:
#          record: true
#          parallel: true
#          browser: firefox
#          config: "specPattern=**/Done/*.feature,viewportWidth=375,viewportHeight=667"
#          group: "Firefox - Mobile"
#        env:
#          # pass the Dashboard record key as an environment variable
#          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
#          # pass GitHub token to allow accurately detecting a build vs a re-run build
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      - name: Upload test results
#        run: npm run upload-test-results
#        env:
#          # pass the Xray credentials as environment variables
#          XRAY_API_CLIENT_ID: ${{ secrets.XRAY_API_CLIENT_ID }}
#          XRAY_API_CLIENT_SECRET: ${{ secrets.XRAY_API_CLIENT_SECRET }}

#  cypress-edge-tablet:
#    runs-on: ubuntu-latest
#    container:
#      image: cypress/browsers:node16.14.0-edge
#      options: --user 1001
#    strategy:
#      # when one test fails, DO NOT cancel the other
#      # containers, because this will kill Cypress processes
#      # leaving the Dashboard hanging ...
#      # https://github.com/cypress-io/github-action/issues/48
#      fail-fast: false
#      matrix:
#        # run 3 copies of the current job in parallel
#        containers: [ 1, 2, 3 ]
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3.5.0
#      # Install NPM dependencies, cache them correctly
#      # and run all Cypress tests
#      - name: Cypress run
#        uses: cypress-io/github-action@v4.1.1
#        with:
#          record: true
#          parallel: true
#          browser: edge
#          config: "specPattern=**/Done/*.feature,viewportWidth=950,viewportHeight=600"
#          group: "Edge - Tablet"
#        env:
#          # pass the Dashboard record key as an environment variable
#          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
#          # pass GitHub token to allow accurately detecting a build vs a re-run build
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      - name: Upload test results
#        run: npm run upload-test-results
#        env:
#          # pass the Xray credentials as environment variables
#          XRAY_API_CLIENT_ID: ${{ secrets.XRAY_API_CLIENT_ID }}
#          XRAY_API_CLIENT_SECRET: ${{ secrets.XRAY_API_CLIENT_SECRET }}