name: Run Cypress Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  cypress-tests:
    uses: ./.github/workflows/execute-cypress-test-suite.yaml
    secrets: inherit

  prepare-test-report:
    if: success() || failure()
    needs: [
      cypress-tests,
    ]
    uses: ./.github/workflows/prepare-test-report.yaml

  create-html-report:
    if: success() || failure()
    needs: [
      prepare-test-report,
    ]
    uses: ./.github/workflows/create-fancy-html-report.yaml

  sync-results-to-xray:
    if: success() || failure()
    needs: [
      prepare-test-report,
    ]
    uses: ./.github/workflows/upload-test-results-to-xray.yaml
    secrets: inherit
