name: Run Cypress Tests

on: [push]

jobs:
  cypress-tests:
    uses: ./.github/workflows/execute-cypress-test-suite.yaml
    secrets: inherit

  create-test-reports:
    if: success() || failure()
    needs: [
      cypress-tests,
    ]
    uses: ./.github/workflows/create-fancy-html-report.yaml

  upload-test-results:
    if: success() || failure()
    needs: [
      cypress-tests,
    ]
    uses: ./.github/workflows/upload-test-results-to-xray.yaml
    secrets: inherit
